In [1]:
import numpy as np

Operations on Arrays

In [2]:
array1 = np.array([[3,6],[4,2]])
array2 = np.array([[10,20],[15,12]])


In [3]:
array1 + array2

array([[13, 26],
       [19, 14]])

In [4]:
array1 - array2

array([[ -7, -14],
       [-11, -10]])

In [5]:
array1 * array2

array([[ 30, 120],
       [ 60,  24]])

In [6]:
#Matrix Multiplication
array1 @ array2

array([[120, 132],
       [ 70, 104]])

In [7]:
#Exponentiation
array1 ** 3

array([[ 27, 216],
       [ 64,   8]], dtype=int32)

In [8]:
#Division
array2 / array1

array([[3.33333333, 3.33333333],
       [3.75      , 6.        ]])

In [9]:
#Element wise Remainder of Division
#(Modulo)
array2 % array1

array([[1, 2],
       [3, 0]])

In [10]:
#Transpose
array3 = np.array([[10,-7,0, 20],
[-5,1,200,40],[30,1,-1,4]])
array3

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [11]:
array3.transpose()

array([[ 10,  -5,  30],
       [ -7,   1,   1],
       [  0, 200,  -1],
       [ 20,  40,   4]])

In [12]:
#Sorting
array4 = np.array([1,0,2,-3,6,8,4,7])
array4.sort()
array4

array([-3,  0,  1,  2,  4,  6,  7,  8])

By default, sorting
is done row-wise (i.e., on axis = 1). It means to arrange
elements in each row in ascending order. When axis=0,
sorting is done column-wise, which means each column
is sorted in ascending order.

In [13]:
array4 = np.array([[10,-7,0, 20],
[-5,1,200,40],[30,1,-1,4]])
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [14]:
array4.sort()
array4

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [15]:
array4 = np.array([[10,-7,0, 20],
[-5,1,200,40],[30,1,-1,4]])
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [19]:
array4.sort(axis=0)
array4

array([[ -5,  -7,  -1,   4],
       [ 10,   1,   0,  20],
       [ 30,   1, 200,  40]])

oncatenating Arrays
Concatenation means joining two or more arrays.
Concatenating 1-D arrays means appending the
sequences one after another. NumPy.concatenate() function can be used to
concatenate two or more
2-D arrays either row-wise or column-wise.

In [21]:
array1 = np.array([[10, 20], [-30,40]])
array2 = np.zeros((2, 3), dtype=array1.dtype)
array1


array([[ 10,  20],
       [-30,  40]])

In [22]:
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
array1.shape

(2, 2)

In [24]:
array2.shape

(2, 3)

In [25]:
np.concatenate((array1,array2), axis=1)

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

In [26]:
np.concatenate((array1,array2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Reshaping Arrays
We can modify the shape of an array using the reshape()
function.

In [16]:
array3 = np.arange(10,22)
array3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [17]:
array3.shape

(12,)

In [18]:
array3.ndim

1

In [19]:
array3.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [20]:
array3.reshape(2,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [21]:
array3.reshape(12,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21]])

In [22]:
array3.reshape(1,12)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

Splitting Arrays
We can split an array into two or more subarrays.
numpy.split() splits an array along the specified axis.
We can either specify sequence of row numbers where an
array is to be split; or we can specify an integer N, that
indicates the number of equal parts in which the array
is to be split, as parameter(s) to the NumPy.split()
function. By default, NumPy.split() splits along axis =
0.

In [23]:
array4

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [24]:
# [1,2] indicate the row indices on which
# to split the array
first, second, third = np.split(array4,[1, 2])
first

array([[10, -7,  0, 20]])

In [25]:
second

array([[ -5,   1, 200,  40]])

In [26]:
third

array([[30,  1, -1,  4]])

In [27]:
arraysplit = array4

In [28]:
arraysplit

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [29]:
a,b = np.split(arraysplit,2)

ValueError: array split does not result in an equal division

In [30]:
a,b = np.split(arraysplit,2,axis=1)

In [31]:
a

array([[10, -7],
       [-5,  1],
       [30,  1]])

In [32]:
b

array([[  0,  20],
       [200,  40],
       [ -1,   4]])

Statistical Operations on Arrays


In [52]:
arrayA = np.array([1,0,2,-3,6,8,4,7])
arrayB = np.array([[3,6],[4,2]])

In [53]:
# max element form the whole 1-D array
arrayA.max()


8

In [54]:

# max element form the whole 2-D array
arrayB.max()

6

In [55]:
# if axis=1, it gives column wise maximum
arrayB.max(axis=1)

array([6, 4])

In [56]:
arrayB

array([[3, 6],
       [4, 2]])

In [57]:
arrayB.max(axis=0)

array([4, 6])