In [1]:
import numpy as np

In [2]:
array1 = np.array([10,20,30]) 
array1

array([10, 20, 30])

Creating a 1-D Array
An array with only single row of elements is called
1-D array. Let us try to create a 1-D array from
a list which contains numbers as well as strings. 


In [3]:
array2 = np.array([5,-7.4,'a',7.2]) #all integer and float values have been promoted to string, while converting the list to array.
print(array2)

['5' '-7.4' 'a' '7.2']


In [4]:
array3 = np.array(  [   [2.4,3], [4.91,7],[0,-1]     ]     )
print(array3)

[[ 2.4   3.  ]
 [ 4.91  7.  ]
 [ 0.   -1.  ]]


Attributes of NumPy Array
ndarray.ndim: gives the number of dimensions
of the array as an integer value. Arrays can be
1-D, 2-D or n-D.  NumPy calls the
dimensions as axes (plural of axis). Thus, a 2-D
array has two axes. The row-axis is called axis-0
and the column-axis is called axis-1. The number
of axes is also called the array’s rank.


In [5]:
array1.ndim


1

In [6]:
array2.ndim

1

In [7]:
array3.ndim

2

ndarray.shape: It gives the sequence of integers
indicating the size of the array for each dimension. 

In [8]:
array1 = np.array([10,20,30]) 
array1.shape

(3,)

In [9]:
array2 = np.array([5,-7.4,'a',7.2])
array2.shape

(4,)

In [14]:
array3 = np.array(  [   [2.4,3], [4.91,7],[0,-1]     ]     )
array3.shape

(3, 2)

ndarray.size: It gives the total number of
elements of the array. This is equal to the product
of the elements of shape.

In [10]:
array1.size

3

In [11]:
array2.size

4

In [12]:
array3.size

6

ndarray.dtype: is the data type of the elements
of the array. All the elements of an array are of
same data type. Common data types are int32,
int64, float32, float64, U32, etc.

In [13]:
array1.dtype

dtype('int32')

In [14]:
array2.dtype

dtype('<U32')

In [15]:
array3.dtype

dtype('float64')

We can specify data type (integer, float, etc.) while
creating array using dtype as an argument to
array(). This will convert the data automatically
to the mentioned type.

In [16]:
array4 = np.array( [ [1,2], [3,4] ],
 dtype=float)
array4

array([[1., 2.],
       [3., 4.]])

In [17]:
array5 = np.zeros((3,4))
array5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
array6 = np.ones((3,2))
array6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
array5 = np.zeros((3,4),dtype= int)
array5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
array6 = np.ones((3,2),dtype= int)
array6

array([[1, 1],
       [1, 1],
       [1, 1]])

We can create an array with numbers in a given
range and sequence using the arange() function.

In [20]:
array7 = np.arange(6) 
array7


array([0, 1, 2, 3, 4, 5])

In [21]:
array8 = np.arange( -2, 24, 4 )
array8

array([-2,  2,  6, 10, 14, 18, 22])

In [22]:
array9 = np.arange( -2, 24 )
array9

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23])

Indexing and Slicing

In [23]:
marks = np.array( [[78,67,56],[76,75,46],[84,59,60],[67,72,54]])
marks

array([[78, 67, 56],
       [76, 75, 46],
       [84, 59, 60],
       [67, 72, 54]])

In [24]:
marks.ndim

2

In [25]:
marks.shape

(4, 3)

In [23]:
marks.size

12

In [24]:
marks[0][2]

56

In [35]:
marks[0][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [36]:
marks[4][2]

IndexError: index 4 is out of bounds for axis 0 with size 4

We can define which part of the
array to be sliced by specifying the start and end index
values using [start : end] along with the array name.

In [27]:
array8 = np.array([-2, 2, 6, 10, 14, 18, 22])
array8

                  

array([-2,  2,  6, 10, 14, 18, 22])

In [28]:
array8[3:6]  #[start : end] but it prints upto "end-1"

array([10, 14, 18])

In [42]:
array8[3:7]

array([10, 14, 18, 22])

In [43]:
array8[3:8]

array([10, 14, 18, 22])

In [29]:
marks = np.array( [[78,67,56],[76,75,46],[84,59,60],[67,72,54]])
marks


array([[78, 67, 56],
       [76, 75, 46],
       [84, 59, 60],
       [67, 72, 54]])

In [48]:
marks[0:4,2]

array([56, 46, 60, 54])

In [49]:
marks[:,:]

array([[78, 67, 56],
       [76, 75, 46],
       [84, 59, 60],
       [67, 72, 54]])

In [50]:
marks[:,1]

array([67, 75, 59, 72])

In [51]:
marks[:,0]

array([78, 76, 84, 67])

In [52]:
marks[:,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [ ]:
marks[:,3]